#!/bin/bash

set -o errexit
set -o nounset


export INTERPOL_ENVS="${INTERPOL_ENVS:-$(env | while read kv; do echo $kv | sed 's/^NOMAD_VAR_//'; done|base64)}"
export NOMAD_VAR_INTERPOL_ENVS=${INTERPOL_ENVS}

echo "$@" > /tmp/rendered.command
args=( "$@" )

if [ 'nomad' = "$1" ] && [ 'run' = "$2" -o 'plan' = "$2" ]
then
  cmd=${args[@]:0:$# -1}
  tmpl=${args[@]: -1}
  interpol "$tmpl" 2 > /tmp/rendered.nomad
  cat /tmp/rendered.nomad
  echo -e '\n'
  exec ${cmd} /tmp/rendered.nomad
else
  exec "$@"
fi
