#!/bin/sh
# shellcheck disable=SC2220

template=""
while getopts t: opt 2>/dev/null
do
  case $opt in
    t) template=$OPTARG;;
    ?) echo "($0): An error with the option specification"
esac done

sed 's/'"'"'/"/g' "$template" > __rendered__.nomad
levant render -out /tmp/rendered.nomad __rendered__.nomad
cat /tmp/rendered.nomad
echo -e '\n'
nomad run -address="${NOMAD_ADDR}" /tmp/rendered.nomad