name: build and push

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make docker-builder-create build/linux_amd64 push DOCKER_LOGIN_CREDENTIALS="--username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}"